/****** Script for SelectTopNRows command from SSMS  ******/

SELECT DATEFROMPARTS(HYEAR, 01, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(JANUARY, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 02, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(FEBRUARY, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 03, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(MARCH, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 04, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(APRIL, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 05, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(MAY, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 06, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(JUNE, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 07, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(JULY, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 08, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(AUGUST, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 09, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(SEPTEMBER, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 10, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(OCTOBER, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 11, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(NOVEMBER, ' ')
UNION ALL
SELECT DATEFROMPARTS(HYEAR, 12, value) AS HOLIDAY_DATE
FROM [SRC_T24].[dbo].[F_HOLIDAY]
     CROSS APPLY STRING_SPLIT(DECEMBER, ' ');