INSERT INTO STG.dbo.CB_CUSTOMER_CONT_DATA 
 (CUST_SRC_SYS_ID, CONT_TYPE, CONT_DATA) 
 SELECT 
  a.CUSTOMER_CODE,
  1 AS CONTACT_TYPE,
  a.TELEPHONE_HOME AS CONTACT_DATA
  FROM SRC_T24.dbo.FBNK_CUSTOMER a WHERE a.TELEPHONE_HOME IS NOT NULL
  UNION ALL
  SELECT 
  a.CUSTOMER_CODE,
  2 AS CONTACT_TYPE,
  a.TELEPHONE_WORK AS CONTACT_DATA
  FROM  SRC_T24.dbo.FBNK_CUSTOMER a WHERE a.TELEPHONE_WORK IS NOT NULL
  UNION ALL
  SELECT 
  a.CUSTOMER_CODE,
  3 AS CONTACT_TYPE,
  a.TELEPHONE_MOBILE AS CONTACT_DATA
  FROM  SRC_T24.dbo.FBNK_CUSTOMER a WHERE a.TELEPHONE_MOBILE IS NOT NULL
  UNION ALL
  SELECT 
  a.CUSTOMER_CODE,
  4 AS CONTACT_TYPE,
  a.EMAIL_ADDRESS AS CONTACT_DATA
  FROM  SRC_T24.dbo.FBNK_CUSTOMER a WHERE a.EMAIL_ADDRESS IS NOT NULL