SELECT
XMLRECORD.value('(/row/@id)[1]', 'nvarchar(35)') AS CARD_TYPE_NO,
XMLRECORD.value('(/row/c1/text())[1]', 'nvarchar(35)') AS CARD_STATUS,
XMLRECORD.value('(/row/c2/text())[1]', 'nvarchar(35)') AS ACCOUNT,
XMLRECORD.value('(/row/c2/text())[2]', 'nvarchar(35)') AS ACCOUNT_2,
XMLRECORD.value('(/row/c2/text())[3]', 'nvarchar(35)') AS ACCOUNT_3,
XMLRECORD.value('(/row/c3/text())[1]', 'nvarchar(35)') AS CURRENCY,
XMLRECORD.value('(/row/c4/text())[1]', 'date') AS ISSUE_DATE,
XMLRECORD.value('(/row/c5/text())[1]', 'date') AS EXPIRY_DATE,
XMLRECORD.value('(/row/c6/text())[1]', 'nvarchar(65)') AS NAME,
XMLRECORD.value('(/row/c7/text())[1]', 'date') AS PIN_ISSUE_DATE,
XMLRECORD.value('(/row/c8/text())[1]', 'decimal (24,2)') AS LIMIT,
XMLRECORD.value('(/row/c9/text())[1]', 'date') AS CANCELLATION_DATE,
XMLRECORD.value('(/row/c14/text())[1]', 'nvarchar(35)') AS LMB_CARD_TYPE,
XMLRECORD.value('(/row/c14[@m="2"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_SUB_TYPE,
XMLRECORD.value('(/row/c14[@m="3"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ACCOUNT_1,
XMLRECORD.value('(/row/c14[@m="4"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ACCOUNT_2,
XMLRECORD.value('(/row/c14[@m="5"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ACCOUNT_3,
XMLRECORD.value('(/row/c14[@m="6"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_URGENT,
XMLRECORD.value('(/row/c14[@m="7"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_HOLDER_CUSTOMER_NO,
XMLRECORD.value('(/row/c14[@m="8"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_HOLDER_NAME,
XMLRECORD.value('(/row/c14[@m="9"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_COMPANY_ID,
XMLRECORD.value('(/row/c14[@m="10"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_COMPANY_NAME,
XMLRECORD.value('(/row/c14[@m="11"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_SECRET_WORD,
XMLRECORD.value('(/row/c14[@m="12"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_BASE_SUPPL,
XMLRECORD.value('(/row/c14[@m="13"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ORDER_TYPE,
XMLRECORD.value('(/row/c14[@m="14"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_CMS_ID,
XMLRECORD.value('(/row/c14[@m="15"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_DELIVERY_BRANCH,
XMLRECORD.value('(/row/c14[@m="16"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_DAILY_LIMIT,
XMLRECORD.value('(/row/c14[@m="17"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_DAO,
XMLRECORD.value('(/row/c14[@m="18"]/text())[1]', 'nvarchar(35)') AS LMB_NOTES,
XMLRECORD.value('(/row/c14[@m="19"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ACTIVATION,
XMLRECORD.value('(/row/c14[@m="20"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_BLOCK,
XMLRECORD.value('(/row/c14[@m="21"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_LIMIT_AMOUNT,
XMLRECORD.value('(/row/c14[@m="22"]/text())[1]', 'date') AS LMB_CARD_LIMIT_EXPIRY_DATE,
XMLRECORD.value('(/row/c14[@m="23"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_ORDER_ID,
XMLRECORD.value('(/row/c14[@m="24"]/text())[1]', 'nvarchar(35)') AS LMB_DS_ID,
XMLRECORD.value('(/row/c14[@m="25"]/text())[1]', 'nvarchar(35)') AS VERSION_NAME,
XMLRECORD.value('(/row/c14[@m="26"]/text())[1]', 'nvarchar(35)') AS LMB_CLOSECCL_DT,
XMLRECORD.value('(/row/c14[@m="27"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_CREDIT_INT,
XMLRECORD.value('(/row/c14[@m="28"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_DEBIT_INT,
XMLRECORD.value('(/row/c14[@m="29"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_CCLFEE,
XMLRECORD.value('(/row/c14[@m="30"]/text())[1]', 'nvarchar(35)') AS CARD_FEE,
XMLRECORD.value('(/row/c14[@m="31"]/text())[1]', 'nvarchar(35)') AS LMB_DR_CR_CARD,
XMLRECORD.value('(/row/c14[@m="32"]/text())[1]', 'nvarchar(35)') AS LMB_PAN_ALIAS,
XMLRECORD.value('(/row/c14[@m="33"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_COND_ID,
XMLRECORD.value('(/row/c14[@m="34"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_PARTNER,
XMLRECORD.value('(/row/c14[@m="35"]/text())[1]', 'nvarchar(35)') AS LMB_PAYMENT_TYPE,
XMLRECORD.value('(/row/c14[@m="36"]/text())[1]', 'decimal (24,2)') AS LMB_CARD_FEE,
XMLRECORD.value('(/row/c14[@m="37"]/text())[1]', 'nvarchar(35)') AS LMB_WAIVE_FEE,
XMLRECORD.value('(/row/c14[@m="38"]/text())[1]', 'decimal (24,2)') AS LMB_ADD_FEE,
XMLRECORD.value('(/row/c14[@m="39"]/text())[1]', 'nvarchar(35)') AS LMB_ADD_WAIVE,
XMLRECORD.value('(/row/c14[@m="40"]/text())[1]', 'decimal (24,2)') AS LMB_URGENT_FEE,
XMLRECORD.value('(/row/c14[@m="41"]/text())[1]', 'nvarchar(35)') AS LMB_URGENT_WAIVE,
XMLRECORD.value('(/row/c14[@m="42"]/text())[1]', 'nvarchar(35)') AS LMB_RECOMMENDED_BY,
XMLRECORD.value('(/row/c14[@m="55"]/text())[1]', 'nvarchar(35)') AS LMB_APPL_ID,
XMLRECORD.value('(/row/c14[@m="56"]/text())[1]', 'nvarchar(35)') AS LMB_CARD_CODE,
XMLRECORD.value('(/row/c14[@m="60"]/text())[1]', 'nvarchar(35)') AS LMB_BLOCK_TYPE,
XMLRECORD.value('(/row/c14[@m="61"]/text())[1]', 'nvarchar(35)') AS LMB_BLOCK_REASON,
XMLRECORD.value('(/row/c14[@m="62"]/text())[1]', 'date') AS LMB_CARD_DEACTIVATION_DATE,
XMLRECORD.value('(/row/c14[@m="63"]/text())[1]', 'nvarchar(35)') AS LMB_INP_BRANCH,
XMLRECORD.value('(/row/c14[@m="64"]/text())[1]', 'nvarchar(35)') AS LMB_K_PAN,
XMLRECORD.value('(/row/c14[@m="65"]/text())[1]', 'date') AS LMB_OPER_DATE,
XMLRECORD.value('(/row/c14[@m="66"]/text())[1]', 'nvarchar(35)') AS LMB_OPER_TYPE,
XMLRECORD.value('(/row/c38/text())[1]', 'nvarchar(35)') AS RECORD_STATUS,
XMLRECORD.value('(/row/c39/text())[1]', 'int') AS CURR_NO,
XMLRECORD.value('(/row/c40/text())[1]', 'nvarchar(65)') AS INPUTTER,
CAST(SUBSTRING(XMLRECORD.value('(/row/c41/text())[1]', 'nvarchar(35)'), 1, 6) AS DATE) AS LAST_UPD_DATE,
XMLRECORD.value('(/row/c42/text())[1]', 'nvarchar(65)') AS AUTHORISER,
XMLRECORD.value('(/row/c43/text())[1]', 'nvarchar(65)') AS CO_CODE,
XMLRECORD.value('(/row/c44/text())[1]', 'nvarchar(65)') AS DEPT_CODE
FROM FBNK_CARD_ISSUE 