SELECT 
XMLRECORD.value('(/row/@id)[1]', 'nvarchar(10)') AS CUSTOMER_CODE, 
XMLRECORD.value('(/row/c2/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c2/text())[2]', 'nvarchar(35)'), '') AS SHORT_NAME,
XMLRECORD.value('(/row/c3/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c3/text())[2]', 'nvarchar(35)'), '') AS NAME_1,
XMLRECORD.value('(/row/c4/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c4/text())[2]', 'nvarchar(35)'), '') AS NAME_2,
XMLRECORD.value('(/row/c23/text())[1]', 'int') AS SECTOR,
XMLRECORD.value('(/row/c24/text())[1]', 'nvarchar(35)') AS ACCOUNT_OFFICER,
XMLRECORD.value('(/row/c26/text())[1]', 'int') AS INDISTRY,
XMLRECORD.value('(/row/c28/text())[1]', 'nvarchar(2)') AS NATIONALITY,
XMLRECORD.value('(/row/c29/text())[1]', 'int') AS CUSTOMER_STATUS,
XMLRECORD.value('(/row/c30/text())[1]', 'nvarchar(2)') AS RESIDENCE,
XMLRECORD.value('(/row/c32/text())[1]', 'nvarchar(35)') AS INTRODUCER,
XMLRECORD.value('(/row/c34/text())[1]', 'nvarchar(35)') AS LEGAL_ID,
XMLRECORD.value('(/row/c35/text())[1]', 'nvarchar(35)') AS LEGAL_DOC_NAME,
XMLRECORD.value('(/row/c36/text())[1]', 'nvarchar(100)') AS LEGAL_HOLDER_NAME,
XMLRECORD.value('(/row/c37/text())[1]', 'nvarchar(35)') AS LEGAL_ISS_AUTH,
XMLRECORD.value('(/row/c38/text())[1]', 'date') AS LEGAL_ISS_DATE,
XMLRECORD.value('(/row/c39/text())[1]', 'date') AS LEGAL_EXP_DATE,
XMLRECORD.value('(/row/c42/text())[1]', 'date') AS BIRTH_INCORP_DATE,
XMLRECORD.value('(/row/c45/text())[1]', 'int') AS LANGUAGE,
XMLRECORD.value('(/row/c63/text())[1]', 'nvarchar(35)') AS GENDER,
XMLRECORD.value('(/row/c65/text())[1]', 'nvarchar(35)') AS MARITAL_STATUS,
XMLRECORD.value('(/row/c66/text())[1]', 'int') AS NO_OF_DEPENDENTS,
XMLRECORD.value('(/row/c70/text())[1]', 'nvarchar(35)') AS EMPLOYMENT_STATUS,
XMLRECORD.value('(/row/c71/text())[1]', 'nvarchar(35)') AS OCCUPATION,
XMLRECORD.value('(/row/c72/text())[1]', 'nvarchar(35)') AS JOB_TITLE,
XMLRECORD.value('(/row/c76/text())[1]', 'date') AS EMPLOYMENT_START,
XMLRECORD.value('(/row/c77/text())[1]', 'nvarchar(35)') AS CUSTOMER_CURRENCY,
CAST(REPLACE(XMLRECORD.value('(/row/c78/text())[1]', 'nvarchar(35)'), ',', '') AS DECIMAL(24, 2)) AS SALARY,
XMLRECORD.value('(/row/c96/text())[1]', 'nvarchar(35)') AS PREVIOUS_NAME,
XMLRECORD.value('(/row/c111/text())[1]', 'nvarchar(35)') AS TAX_ID,
XMLRECORD.value('(/row/c178[@m="16"]/text())[1]', 'nvarchar(35)') AS TELEPHONE_HOME,
XMLRECORD.value('(/row/c178[@m="17"]/text())[1]', 'nvarchar(35)') AS TELEPHONE_WORK,
XMLRECORD.value('(/row/c178[@m="18"]/text())[1]', 'nvarchar(35)') AS TELEPHONE_MOBILE,
XMLRECORD.value('(/row/c178[@m="19"]/text())[1]', 'nvarchar(2)') AS RESIDENT_YN,
XMLRECORD.value('(/row/c178[@m="20"]/text())[1]', 'nvarchar(35)') AS EMAIL_ADDRESS,
XMLRECORD.value('(/row/c178[@m="21"]/text())[1]', 'nvarchar(35)') AS EMPLOYER_NAME,
XMLRECORD.value('(/row/c178[@m="35"]/text())[1]', 'date') AS OPENING_DATE,
XMLRECORD.value('(/row/c178[@m="36"]/text())[1]', 'nvarchar(35)') AS CUST_TYPE,
XMLRECORD.value('(/row/c178[@m="115"]/text())[1]', 'nvarchar(65)') AS EMPLOYER_CODE,
XMLRECORD.value('(/row/c178[@m="151"]/text())[1]', 'int') AS BUSINESS_TYPE,
XMLRECORD.value('(/row/c178[@m="173"]/text())[1]', 'nvarchar(65)') AS CUS_LAST_NAME_AZ,
XMLRECORD.value('(/row/c178[@m="174"]/text())[1]', 'nvarchar(65)') AS CUS_FIRST_NAME_AZ,
XMLRECORD.value('(/row/c178[@m="175"]/text())[1]', 'nvarchar(65)') AS CUS_MID_NAME_AZ,
XMLRECORD.value('(/row/c178[@m="182"]/text())[1]', 'nvarchar(200)') AS PHYSICAL_ADDRESS,
XMLRECORD.value('(/row/c178[@m="183"]/text())[1]', 'nvarchar(2)') AS PHYSICAL_ADDRESS_COUNTRY,
XMLRECORD.value('(/row/c178[@m="199"]/text())[1]', 'nvarchar(35)') AS VERSION,
XMLRECORD.value('(/row/c178[@m="214"]/text())[1]', 'nvarchar(65)') AS PLACE_OF_BIRTH,
XMLRECORD.value('(/row/c178[@m="222"]/text())[1]', 'nvarchar(2)') AS POLITICALLY_EXPOSED_PERSON,
XMLRECORD.value('(/row/c178[@m="228"]/text())[1]', 'int') AS SUBTYPE_OF_INDUSTRY,
XMLRECORD.value('(/row/c178[@m="238"]/text())[1]', 'nvarchar(200)') AS LEGAL_ADDRESS,
XMLRECORD.value('(/row/c178[@m="239"]/text())[1]', 'nvarchar(35)') AS LEGAL_ADDRESS_COUNTRY,
XMLRECORD.value('(/row/c178[@m="241"]/text())[1]', 'nvarchar(200)') AS LEGAL_ADDRESS_SWIFT_ADDRESS,
XMLRECORD.value('(/row/c178[@m="245"]/text())[1]', 'nvarchar(35)') AS LEGAL_ADDRESS_ZONE,
XMLRECORD.value('(/row/c178[@m="246"]/text())[1]', 'nvarchar(35)') AS LEGAL_ADDRESS_CITY,
XMLRECORD.value('(/row/c178[@m="249"]/text())[1]', 'nvarchar(35)') AS LEGAL_ADDRESS_DISTRICT,
XMLRECORD.value('(/row/c178[@m="250"]/text())[1]', 'nvarchar(35)') AS PHYSICAL_ADDRESS_ZONE,
XMLRECORD.value('(/row/c178[@m="251"]/text())[1]', 'nvarchar(35)') AS PHYSICAL_ADDRESS_CITY,
XMLRECORD.value('(/row/c178[@m="252"]/text())[1]', 'nvarchar(35)') AS PHYSICAL_ADDRESS_DISTRICT,
XMLRECORD.value('(/row/c178[@m="309"]/text())[1]', 'nvarchar(35)') AS RESPONSIBLE_OFFICER,
XMLRECORD.value('(/row/c181/text())[1]', 'int') AS CURR_NO,
XMLRECORD.value('(/row/c182/text())[1]', 'nvarchar(65)') AS INPUTTER,
CAST(SUBSTRING(XMLRECORD.value('(/row/c183/text())[1]', 'nvarchar(35)'), 1, 6) AS DATE) AS LAST_UPD_DATE,
XMLRECORD.value('(/row/c184/text())[1]', 'nvarchar(65)') AS AUTHORISER,
XMLRECORD.value('(/row/c185/text())[1]', 'nvarchar(65)') AS CO_CODE,
XMLRECORD.value('(/row/c186/text())[1]', 'nvarchar(65)') AS DEPT_CODE
FROM 
FBNK_CUSTOMER a