SELECT LEFT(XMLRECORD.value('(/row/@id)[1]', 'nvarchar(35)'), CHARINDEX(';', XMLRECORD.value('(/row/@id)[1]', 'nvarchar(35)'))-1) AS REF_NO,
       XMLRECORD.value('(/row/c1/text())[1]', 'nvarchar(35)') AS TRANSACTION_TYPE,
       XMLRECORD.value('(/row/c2/text())[1]', 'nvarchar(35)') AS DEBIT_ACCT_NO,
       XMLRECORD.value('(/row/c3/text())[1]', 'nvarchar(35)') AS IN_DEBIT_ACCT_NO,
       XMLRECORD.value('(/row/c5/text())[1]', 'nvarchar(35)') AS DEBIT_CURRENCY,
       XMLRECORD.value('(/row/c6/text())[1]', 'decimal(24,2)') AS DEBIT_AMOUNT,
       XMLRECORD.value('(/row/c7/text())[1]', 'date') AS DEBIT_VALUE_DATE,
       XMLRECORD.value('(/row/c8/text())[1]', 'date') AS IN_DEBIT_VDATE,
       XMLRECORD.value('(/row/c9/text())[1]', 'nvarchar(35)') AS DEBIT_THEIR_REF,
       XMLRECORD.value('(/row/c10/text())[1]', 'nvarchar(35)') AS CREDIT_THEIR_REF,
       XMLRECORD.value('(/row/c11/text())[1]', 'nvarchar(35)') AS CREDIT_ACCT_NO,
       XMLRECORD.value('(/row/c13/text())[1]', 'nvarchar(35)') AS CREDIT_CURRENCY,
       XMLRECORD.value('(/row/c14/text())[1]', 'decimal(24,2)') AS CREDIT_AMOUNT,
       XMLRECORD.value('(/row/c15/text())[1]', 'date') AS CREDIT_VALUE_DATE,
       XMLRECORD.value('(/row/c18/text())[1]', 'date') AS PROCESSING_DATE,
       XMLRECORD.value('(/row/c19/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c19/text())[2]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c19/text())[3]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c19/text())[4]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c19/text())[5]', 'nvarchar(35)'), '') AS ORDERING_CUST,
       XMLRECORD.value('(/row/c21/text())[1]', 'nvarchar(35)') AS ORDERING_BANK,
	   XMLRECORD.value('(/row/c25/text())[1]', 'nvarchar(35)') AS BEN_ACCT_NO,
       XMLRECORD.value('(/row/c27/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c27/text())[2]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c27/text())[3]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c27/text())[4]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c27/text())[5]', 'nvarchar(35)'), '') AS BEN_CUSTOMER,
       XMLRECORD.value('(/row/c32/text())[1]', 'nvarchar(35)')+COALESCE(XMLRECORD.value('(/row/c32/text())[2]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c32/text())[3]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c32/text())[4]', 'nvarchar(35)'), '')+COALESCE(XMLRECORD.value('(/row/c32/text())[5]', 'nvarchar(35)'), '') AS PAYMENT_DETAILS,
       XMLRECORD.value('(/row/c40/text())[1]', 'nvarchar(35)') AS PAY_MENTHOD,
       XMLRECORD.value('(/row/c41/text())[1]', 'nvarchar(35)') AS BEN_OUR_CHARGES,
       XMLRECORD.value('(/row/c67[@m="20"]/text())[1]', 'nvarchar(65)') AS DEBIT_FULL_NAME,
       XMLRECORD.value('(/row/c67[@m="22"]/text())[1]', 'nvarchar(65)') AS CREDIT_FULL_NAME,
       XMLRECORD.value('(/row/c67[@m="50"]/text())[1]', 'nvarchar(65)') AS NARRATIVE_LOCAL,
       XMLRECORD.value('(/row/c67[@m="81"]/text())[1]', 'nvarchar(65)') AS LMB_DESCRIPTION,
       XMLRECORD.value('(/row/c176/text())[1]', 'nvarchar(35)') AS RECORD_STATUS,
       XMLRECORD.value('(/row/c177/text())[1]', 'int') AS CURR_NO
FROM FBNK_FUNDS_TRANSFER#HIS;