SELECT
XMLRECORD.value('(/row/@id)[1]', 'nvarchar(35)') AS SPEC_ENTRY_KEY,
XMLRECORD.value('(/row/c1/text())[1]', 'nvarchar(35)') AS DEAL_NUMBER,
XMLRECORD.value('(/row/c2/text())[1]', 'nvarchar(35)') AS COMPANY_CODE,
XMLRECORD.value('(/row/c3/text())[1]', 'decimal(24,2)') AS AMOUNT_LCY,
XMLRECORD.value('(/row/c4/text())[1]', 'nvarchar(35)') AS TRANSACTION_CODE,
XMLRECORD.value('(/row/c5/text())[1]', 'nvarchar(35)') AS CONSOL_KEY_TYPE,
XMLRECORD.value('(/row/c6/text())[1]', 'nvarchar(65)') AS NARRATIVE,
XMLRECORD.value('(/row/c7/text())[1]', 'nvarchar(35)') AS PL_CATEGORY,
XMLRECORD.value('(/row/c8/text())[1]', 'nvarchar(35)') AS CUSTOMER_ID,
XMLRECORD.value('(/row/c10/text())[1]', 'nvarchar(35)') AS PRODUCT_CATEGORY,
XMLRECORD.value('(/row/c11/text())[1]', 'date') AS VALUE_DATE,
XMLRECORD.value('(/row/c12/text())[1]', 'nvarchar(35)') AS CURRENCY,
XMLRECORD.value('(/row/c13/text())[1]', 'decimal(24,2)') AS AMOUNT_FCY,
XMLRECORD.value('(/row/c14/text())[1]', 'decimal(24,2)') AS EXCHANGE_RATE,
XMLRECORD.value('(/row/c17/text())[1]', 'nvarchar(35)') AS OUR_REFERENCE,
XMLRECORD.value('(/row/c24/text())[1]', 'nvarchar(35)') AS SYSTEM_ID,
XMLRECORD.value('(/row/c30/text())[1]', 'nvarchar(65)') AS INPUTTER,
XMLRECORD.value('(/row/c28/text())[1]', 'nvarchar(35)') AS RECORD_STATUS,
XMLRECORD.value('(/row/c29/text())[1]', 'int') AS CURR_NO
FROM FBNK_RE_C018